//
//  MyDetailViewController.swift
//  CIS22C_LAB2
//
//  Created by Brian Lim on 10/24/16.
//  Copyright © 2016 Brian Lim. All rights reserved.
//

import UIKit

class MyDetailViewController: UIViewController {

    @IBOutlet var LabelText: UILabel!
    @IBOutlet var LabelImage: UIImageView!
    @IBOutlet var AnimalFacts: UITextView!
    
    var LabelTextText : String!
    var LabelImageText : String!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        self.LabelText.text = self.LabelTextText
        self.LabelImage.image = UIImage(named: self.LabelImageText)
        
        //if labeltext == "name" -> AnimalFacts = "text"
        switch LabelTextText
        {
            case "Akita":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Name: Akita  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Origin: Japan  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Size (L):71cm (28in)  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Weight: 50kg (110lbs)  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Life Span: 10 years  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 7  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Working  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Brown, White, Black, Grey  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Temperament: Intelligent, courageous and fearless  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Training: Medium - Hard  \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Pointed ears and upward curving tail \n\n"
            case "Baboon":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Primates \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Cercopithecidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Papio \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Papio \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: Baboon \n\n"
                AnimalFacts.text = AnimalFacts.text + "Other Name(s): Olive Baboon, Yellow Baboon, Guinea Baboon, Chacma Baboon, Hamadryas Baboon \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Number Of Species: 5 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Location: Africa and Western Arabia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Grassland, rocky desert and rainforest \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Olive, Yellow, Grey, Silver, Brown, Black \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Hair \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 50cm - 86cm (20in - 34in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 14kg - 45kg (30lbs - 100lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 45kph (30mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Prey: Fruits, Seeds, Insects \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Lion, Leopard, African Wild Dog \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Diurnal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group Behaviour: Troop \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 15 - 40 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Sexual Maturity: 5 - 7years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Gestation Period: 170 days \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Name Of Young: Infant \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Weaning: 6 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Estimated Population Size: Decreasing \n\n"
                AnimalFacts.text = AnimalFacts.text + "Biggest Threat: Hunting and habitat loss \n\n"
                AnimalFacts.text = AnimalFacts.text + "Most Distinctive Feature: Dog-like muzzle and long, bent tail \n\n"
                AnimalFacts.text = AnimalFacts.text + "Fun Fact: Can travel more than four miles a day! \n\n"
            
            case "Caiman":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Reptilia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Crocodilia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Alligatoridae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Caimaninae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Caimaninae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Reptile \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (L): 1.1m - 5m (43in - 197in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 100kg - 500kg (220lbs - 1,102lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 48km/h (30mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 30 - 40 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Green, Brown, Black, Grey \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Scales \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Mangroves, marshes and swamps \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 30 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Fish, Insects, Birds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Humans, Jaguars \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Narrow body shape and long tail \n\n"
            
            case "Dachshund":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Name: Dachshund \n\n"
                AnimalFacts.text = AnimalFacts.text + "Origin: Germany \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 38cm (15in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 4kg (9lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 15 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Hound \n\n"
            
            case "Eagle":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Falconiformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Accipitridae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Hieraatus Spilogaster \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 40cm - 100cm (15.7in - 39.3in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Wing Span: 70cm - 250cm (27.5in - 98in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 0.5kg - 7kg (1.1lbs - 15.4lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 160km/h (100mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 15 - 30 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, Grey, Brown, White, Yellow \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Open waters like rivers, lakes and coastal regions \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 2 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Fish, Mammals, Reptiles \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Human, Hawk, Raccoon \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Long curved beak and strong, sharp claws \n\n"
            
            case "Falcon":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Falconiformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Falconidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Falco \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Falconiforme \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 22cm - 40cm (9in - 19in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Wingspan: 51cm - 110cm (20in - 43in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 0.7kg - 1.2kg (1.5lbs - 2.6lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 322km/h (200mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 12 - 18 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, Grey, Brown, White, Yellow \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Birds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: High areas like mountains and cliffs \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 3 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Birds, Rabbits, Bats \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Human, Eagles, Owls, Wolves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Sharp, pointed beak and aerodynamic body shape \n\n"
            
            case "Galapagos Penguin":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Sphenisciformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Spheniscidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Spheniscus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Spheniscus Mendiculus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 48cm - 50cm (19in - 20in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 2kg - 4kg (4.4lbs - 8.8lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 15 - 20 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Colony \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Endangered \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, White, Grey \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Krill \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Rocky Ocean Islands \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 2 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Krill, Fish, Shrimp \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Leopard Seal, Killer Whale, Sharks \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Small body size and fully black head \n\n"

            case "Hammerhead Shark":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Chondrichthyes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Carcharhiniformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Sphyrnidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Sphyrna \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Sphyrna Zygaena \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 3.5-6m (11.5-20ft) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 230-450kg (500-1000lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 40km/h (25mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 20-25 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Herd \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Grey, Brown, White \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Smooth \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Warm waters and continental shelves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 26 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Fish, Squid, Octopus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Tiger Shark, Great White Shark, Killer Whale \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Broad, flat head and large eyes \n\n"

            case "Ibis":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Ciconiiformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Threskiornithidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Threskiornithidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 50cm - 65cm (19.7in - 25in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Wing Span: 80cm - 120cm (32in - 47in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 0.3kg - 2kg (0.6lbs - 4lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 8 - 15 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Flock \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, White, Grey, Brown \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Marshes, wetlands and swamps \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 2 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Fish, Crab, Insects \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Falcon, Hawks, Herons \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Rounded body and long neck and beak \n\n"
            
            case "Jack Russel":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Name: Jack Russel \n\n"
                AnimalFacts.text = AnimalFacts.text + "Origin: Germany \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 25cm (10in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 4kg (8lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 16 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Terrier \n\n"
            
            case "Kakapo":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Psittaciformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Nestoridae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Strigops \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Strigops Habroptilus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Herbivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 50-60cm (19.7-24in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 2-4kg (4.5-9lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 50-65 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Endangered \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Green, Brown \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Rimu fruit \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Areas of natural vegetation and dense jungle \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 2 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Rimu fruit, Flowers, Roots, Seeds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Human, Cats, Stoats \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Large body size and unable to fly \n\n"
            
            case "Labradoodle":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Name: Labradoodle \n\n"
                AnimalFacts.text = AnimalFacts.text + "Origin: Australia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 50cm (20in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 34kg (75lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 12 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Hybrid Dog \n\n"
            
            case "Macaroni Penguin":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Sphenisciformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Spheniscidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Eudyptes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Eudyptes Chrysolophus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 60-70cm (24-28in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Wing Span: 80-100cm (31-39in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 3.2-6.4kg (7-14lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 35km/h (22mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 15-20 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Colony \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, White, Brown, Yellow \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Sea and ice-islands in Sub-Antarctica \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 2 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Fish, Squid, Crustaceans \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Leopard Seal, Killer Whale \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Large red beak and yellow feathers on head \n\n"
            
            case "Newt":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Lissamphibia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Caudata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Salamandridae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Pleurodelinae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Lissotriton Vulgaris \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Amphibian \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 5-15cm (1.7-5.9in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 10-50g (0.3-1.8oz) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 42km/h (30mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 2-15 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, Brown, Grey, Green, Orange, Red, Yellow \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Scales \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Worms \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Temperate forests and river banks \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 100 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Worms, Insects, Water snails \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Birds, Fox, Reptiles \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Permeable, toxic skin and feathery gills \n\n"
            
            case "Ocelot":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Carnivora \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Felidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Leopardus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Leopardus pardalis \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: Ocelot \n\n"
                AnimalFacts.text = AnimalFacts.text + "Other Name(s): Painted Leopard \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Number Of Species: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Location: South America \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Tropical jungle, grassland and marshes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Tan, Yellow, Red, Grey, Black \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (L): 55cm - 100cm (22in - 40in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 11.5kg - 16kg (25lbs - 35lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 61kph (38mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Prey: Rodents, Lizards, Deer \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Jaguar, Puma, Harpy Eagle \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Nocturnal/Crepuscular \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group Behaviour: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 8 - 12 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Sexual Maturity: 2 - 3 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Gestation Period: 79 - 85 days \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 2 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Name Of Young: Kitten \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Weaning: 6 weeks \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Estimated Population Size: 800,000 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Biggest Threat: Habitat loss \n\n"
                AnimalFacts.text = AnimalFacts.text + "Most Distinctive Feature: Rosettes, spots and stripes on fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Fun Fact: Also known as the Painted Leopard! \n\n"
            
            case "Pademelon":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Diprotodontia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Macropodidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Thylogale \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Thylogale \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Herbivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 42-52cm (16.5-20.5in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 3.5-12kg (7.7-26lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 55km/h (34mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 4-8 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, Brown, Grey, Red \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Grasses \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Dense rainforest and shrubland \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Grasses, Herbs, Shoots \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Foxes, Dogs, Dingos \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Pointed nose and short, thick tail \n\n"
            
            case "Quail":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Aves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Galliformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Phasianidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Coturnix \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Coturnix Coturnix \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Bird \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 11cm - 20cm (4.5in - 7.8in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Wing Span: 30cm - 37cm (12in - 14.6in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 70g - 140g (2.4oz - 4.9oz) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 24km/h (15mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 3 - 5 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Brown, Black, White, Blue \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Feathers \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Seeds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Woodland and forest areas \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 6 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Seeds, Flowers, Insects \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Cats, Snakes, Raccoons \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Small body size and brightly coloured eggs \n\n"

            case "Rabbit":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Lagomorpha \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Leporidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Oryctolagus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Oryctolagus cuniculus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Herbivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 20-50cm (8-20in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 0.5-3kg (1.1-6.6lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 4km/h (2.4mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 4-8 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Group \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Brown, Tan, Grey, Black, White \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Clover \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Forest thickets, meadows and woodland \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 6 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Clover, Grass, Crunchy vegetables \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Fox, Snakes, Large Birds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Long, pointed ears and acute sight, smell and taste \n\n"
            
            case "Saint Benard":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Name: Saint Bernard \n\n"
                AnimalFacts.text = AnimalFacts.text + "Origin: Switzerland \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 102cm (40in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 91kg (200lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 10 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Mastiff \n\n"
            
            case "Tang":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Actinopterygii \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Perciformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Acanthuridae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Zebrasoma \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: Tang \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Acanthuridae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Origin: Indian, Pacific Oceans \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (L): 15cm - 40cm (6in - 16in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Water Type: Salt \n\n"
                AnimalFacts.text = AnimalFacts.text + "Optimum pH Level: 8.0 - 8.5 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 8 - 12 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, Yellow, Red, Blue, Silver \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Scales \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Algae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Shallow tropical coral reefs \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Clutch Size: 40,000 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Algae, Fish, Plankton \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Fish, Eels, Crustaceans \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Pointed snout and razor-sharp scalpel at the base of their tail \n\n"
            
            case "Uakari":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Primates \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Pitheciidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Cacajao \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Cacajao \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: Uakari \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Number Of Species: 4 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Location: Amazon River Basin \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Part-flooded rainforest \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Red, Brown, White, Black \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (L): 38cm - 57cm (15in - 22.5in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 3kg - 3.5kg (6.5lbs - 7.75lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Prey: Fruits, Leaves, Insects \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Hawks, Snakes, Humans \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Diurnal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group Behaviour: Troop \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 16 - 22 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Sexual Maturity: 3 - 6 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Gestation Period: Unknown \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Name Of Young: Infant \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Weaning: 3 - 5 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Vulnerable \n\n"
                AnimalFacts.text = AnimalFacts.text + "Estimated Population Size: Not Known \n\n"
                AnimalFacts.text = AnimalFacts.text + "Biggest Threat: Hunting and habitat loss \n\n"
                AnimalFacts.text = AnimalFacts.text + "Most Distinctive Feature: Hairless face and forehead \n\n"
                AnimalFacts.text = AnimalFacts.text + "Fun Fact: Have a very short tail for their size! \n\n"
            
            case "Vampire Bat":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Chiroptera \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Phyllostomidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Desmodontinae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: Vampire Bat \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Number Of Species: 3 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Location: Central and South America \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Tropical and subtropical regions \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Brown, Grey, Black \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 7cm - 9.5cm (2.75in - 3.75in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Wing Span: 15cm - 18cm (5.9in - 7in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 19g - 57g (0.7oz - 2oz) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 40km/h (25mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Carnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Prey: Cows, Pigs, Tapir \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Eagles. Hawks, Humans \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Nocturnal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group Behaviour: Solitary \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 8 - 12 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Sexual Maturity: 9 - 10 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Gestation Period: 3 - 4 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Name Of Young: Pup \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Weaning: 3 - 5 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Estimated Population Size: Sustainable \n\n"
                AnimalFacts.text = AnimalFacts.text + "Biggest Threat: Habitat loss \n\n"
                AnimalFacts.text = AnimalFacts.text + "Most Distinctive Feature: Razor-sharp front teeth \n\n"
                AnimalFacts.text = AnimalFacts.text + "Fun Fact: Have a heat sensor on the end of their nose! \n\n"
            
            case "Wallaby":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Diprotodontia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Macropodidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Macropus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Macropus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Herbivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 30-180cm (12-71in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 1-20kg (2.2-44lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 48km/h (30mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 12-15 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Herd \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Grey, Brown, White, Tan, Red \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Fur \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Grasses \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Forest and shrubland \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Grasses, Fruits, Seeds, Leaves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Dingo, Fox, Large reptiles \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Very sociable animal with a long tail \n\n"
            
            case "X-Ray Tetra":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Actinopterygii \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Characiformes \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Characidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Pristella \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Pristella maxillaris \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: X-Ray Tetra \n\n"
                AnimalFacts.text = AnimalFacts.text + "Other Name(s): Golden Pristella Tetra, Water Goldfinch \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Fish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Number Of Species: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Location: Brazil, Guiana, Guyana, and Venezuela \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Amazon coastal waters \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Silver, Yellow, Black, White \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Scales \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (H): 3.2cm - 5cm (1.6in - 1.9in) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Omnivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Prey: Worms, Insects, Small Crustaceans \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Larger Fish, Frogs, Birds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Diurnal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group Behaviour: School \n\n"
                AnimalFacts.text = AnimalFacts.text + "Water Type: Fresh, Brackish \n\n"
                AnimalFacts.text = AnimalFacts.text + "Optimum pH Level: 6.0 - 7.0 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 2 - 5 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Sexual Maturity: 5 - 8 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Incubation Period: 24 hours \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Spawn Size: 350 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Name Of Young: Fry \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Independence: Immediately \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Not Listed \n\n"
                AnimalFacts.text = AnimalFacts.text + "Estimated Population Size: Abundant \n\n"
                AnimalFacts.text = AnimalFacts.text + "Biggest Threat: Water Pollution \n\n"
                AnimalFacts.text = AnimalFacts.text + "Distinctive Features: Striped fins and translucent skin \n\n"
                AnimalFacts.text = AnimalFacts.text + "Fun Fact: Yellow, black and white striped fins! \n\n"

            case "Yak":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Artiodactyla \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Bovidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Bos \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Bos Grunniens \n\n"
                AnimalFacts.text = AnimalFacts.text + "Type: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Herbivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size: 2-2.2m (6.5-7.2ft) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 300-1,000kg (661-2,200lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 40km/h (25mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 15-20 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Herd \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Threatened \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Brown, Black, White \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Hair \n\n"
                AnimalFacts.text = AnimalFacts.text + "Favourite Food: Grass \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Alpine meadows and open hills \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Main Prey: Grass, Herbs, Mosses \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Human, Bears, Wolves \n\n"
                AnimalFacts.text = AnimalFacts.text + "Special Features: Thick, hairy coat and large horns \n\n"
            
            case "Zebra":
                AnimalFacts.text = ""
                AnimalFacts.text = AnimalFacts.text + "Kingdom: Animalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Phylum: Chordata \n\n"
                AnimalFacts.text = AnimalFacts.text + "Class: Mammalia \n\n"
                AnimalFacts.text = AnimalFacts.text + "Order: Perissodactyla \n\n"
                AnimalFacts.text = AnimalFacts.text + "Family: Equidae \n\n"
                AnimalFacts.text = AnimalFacts.text + "Genus: Equus \n\n"
                AnimalFacts.text = AnimalFacts.text + "Scientific Name: Equus zebra, Equus quagga, Equus grevyi \n\n"
                AnimalFacts.text = AnimalFacts.text + "Common Name: Zebra \n\n"
                AnimalFacts.text = AnimalFacts.text + "Other Name(s): Mountain Zebra, Common Zebra, Plains Zebra, Burchells Zebra, Grevys Zebra \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group: Mammal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Number Of Species: 3 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Location: Eastern and Southern Africa \n\n"
                AnimalFacts.text = AnimalFacts.text + "Habitat: Open grassland and plains \n\n"
                AnimalFacts.text = AnimalFacts.text + "Colour: Black, White, Brown \n\n"
                AnimalFacts.text = AnimalFacts.text + "Skin Type: Hair \n\n"
                AnimalFacts.text = AnimalFacts.text + "Size (L): 2m - 2.75m (6.6ft - 9ft) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Weight: 220kg - 405kg (485lbs - 893lbs) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Top Speed: 40kph (25mph) \n\n"
                AnimalFacts.text = AnimalFacts.text + "Diet: Herbivore \n\n"
                AnimalFacts.text = AnimalFacts.text + "Prey: Grasses, Leaves, Buds \n\n"
                AnimalFacts.text = AnimalFacts.text + "Predators: Lions, Leopards, Hyenas \n\n"
                AnimalFacts.text = AnimalFacts.text + "Lifestyle: Diurnal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Group Behaviour: Herd \n\n"
                AnimalFacts.text = AnimalFacts.text + "Life Span: 20 - 30 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Sexual Maturity: 3 - 4 years \n\n"
                AnimalFacts.text = AnimalFacts.text + "Gestation Period: 10 - 12 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Average Litter Size: 1 \n\n"
                AnimalFacts.text = AnimalFacts.text + "Name Of Young: Foal \n\n"
                AnimalFacts.text = AnimalFacts.text + "Age Of Weaning: 11 months \n\n"
                AnimalFacts.text = AnimalFacts.text + "Conservation Status: Endangered/Least Concern \n\n"
                AnimalFacts.text = AnimalFacts.text + "Estimated Population Size: Declining \n\n"
                AnimalFacts.text = AnimalFacts.text + "Biggest Threat: Habitat loss \n\n"
                AnimalFacts.text = AnimalFacts.text + "Most Distinctive Feature: Long, slender legs and one toe on each foot \n\n"
                AnimalFacts.text = AnimalFacts.text + "Fun Fact: Stripe patterns are unique to each individual! \n\n"

            default:
                AnimalFacts.text = "Something went wrong.  \n\nContact the owner of the app and explain the error!"
            
        }
        self.view.backgroundColor = UIColor(patternImage: UIImage(named: "animalbackground")!)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
